sudo: required
services:
  - docker

before_install:
  - docker build -t amosshahar-dockersimpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true amosshahar-dockersimpleweb npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "amos-simple-web"
  env: "AmosSimpleWeb-env"
  bucket_name: "elasticbeanstalk-us-west-1-717898102007"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
